// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// BulkUpsert provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) BulkUpsert(products []*Product) error {
	ret := _mock.Called(products)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*Product) error); ok {
		r0 = returnFunc(products)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepository_BulkUpsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsert'
type MockProductRepository_BulkUpsert_Call struct {
	*mock.Call
}

// BulkUpsert is a helper method to define mock.On call
//   - products []*Product
func (_e *MockProductRepository_Expecter) BulkUpsert(products interface{}) *MockProductRepository_BulkUpsert_Call {
	return &MockProductRepository_BulkUpsert_Call{Call: _e.mock.On("BulkUpsert", products)}
}

func (_c *MockProductRepository_BulkUpsert_Call) Run(run func(products []*Product)) *MockProductRepository_BulkUpsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*Product
		if args[0] != nil {
			arg0 = args[0].([]*Product)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProductRepository_BulkUpsert_Call) Return(err error) *MockProductRepository_BulkUpsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepository_BulkUpsert_Call) RunAndReturn(run func(products []*Product) error) *MockProductRepository_BulkUpsert_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Create(product *Product) error {
	ret := _mock.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Product) error); ok {
		r0 = returnFunc(product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - product *Product
func (_e *MockProductRepository_Expecter) Create(product interface{}) *MockProductRepository_Create_Call {
	return &MockProductRepository_Create_Call{Call: _e.mock.On("Create", product)}
}

func (_c *MockProductRepository_Create_Call) Run(run func(product *Product)) *MockProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Product
		if args[0] != nil {
			arg0 = args[0].(*Product)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProductRepository_Create_Call) Return(err error) *MockProductRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepository_Create_Call) RunAndReturn(run func(product *Product) error) *MockProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) FindById(id int) (*Product, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*Product, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *Product); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockProductRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id int
func (_e *MockProductRepository_Expecter) FindById(id interface{}) *MockProductRepository_FindById_Call {
	return &MockProductRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockProductRepository_FindById_Call) Run(run func(id int)) *MockProductRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProductRepository_FindById_Call) Return(product *Product, err error) *MockProductRepository_FindById_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepository_FindById_Call) RunAndReturn(run func(id int) (*Product, error)) *MockProductRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) GetAll() ([]*Product, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*Product, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*Product); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockProductRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockProductRepository_Expecter) GetAll() *MockProductRepository_GetAll_Call {
	return &MockProductRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockProductRepository_GetAll_Call) Run(run func()) *MockProductRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProductRepository_GetAll_Call) Return(products []*Product, err error) *MockProductRepository_GetAll_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockProductRepository_GetAll_Call) RunAndReturn(run func() ([]*Product, error)) *MockProductRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Update(product *Product) error {
	ret := _mock.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Product) error); ok {
		r0 = returnFunc(product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - product *Product
func (_e *MockProductRepository_Expecter) Update(product interface{}) *MockProductRepository_Update_Call {
	return &MockProductRepository_Update_Call{Call: _e.mock.On("Update", product)}
}

func (_c *MockProductRepository_Update_Call) Run(run func(product *Product)) *MockProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Product
		if args[0] != nil {
			arg0 = args[0].(*Product)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProductRepository_Update_Call) Return(err error) *MockProductRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepository_Update_Call) RunAndReturn(run func(product *Product) error) *MockProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockLogger
func (_mock *MockLogger) Debug(format string, args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Debug(format interface{}, args ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(format string, args ...interface{})) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(format string, args ...interface{})) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(format string, args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Error(format interface{}, args ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(format string, args ...interface{})) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(format string, args ...interface{})) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(format string, args ...interface{}) {
	if len(args) > 0 {
		_mock.Called(format, args)
	} else {
		_mock.Called(format)
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *MockLogger_Expecter) Info(format interface{}, args ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{format}, args...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(format string, args ...interface{})) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(format string, args ...interface{})) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// Progress provides a mock function for the type MockLogger
func (_mock *MockLogger) Progress(filePath string, processed int, total int, percentage float64) {
	_mock.Called(filePath, processed, total, percentage)
	return
}

// MockLogger_Progress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Progress'
type MockLogger_Progress_Call struct {
	*mock.Call
}

// Progress is a helper method to define mock.On call
//   - filePath string
//   - processed int
//   - total int
//   - percentage float64
func (_e *MockLogger_Expecter) Progress(filePath interface{}, processed interface{}, total interface{}, percentage interface{}) *MockLogger_Progress_Call {
	return &MockLogger_Progress_Call{Call: _e.mock.On("Progress", filePath, processed, total, percentage)}
}

func (_c *MockLogger_Progress_Call) Run(run func(filePath string, processed int, total int, percentage float64)) *MockLogger_Progress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockLogger_Progress_Call) Return() *MockLogger_Progress_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Progress_Call) RunAndReturn(run func(filePath string, processed int, total int, percentage float64)) *MockLogger_Progress_Call {
	_c.Run(run)
	return _c
}
